n_elem = 200 # Number of Elements
T_edge = 700.0 # Temperature at the outer boundary
r = 0.004 # Pellet Radius = 4 mm
k = 5.0 # Value of the constant thermal conductivity
[Mesh]
  [2D_annular]# A mesh of a 2D pellet generated by moose
    type = AnnularMeshGenerator
    rmax = '${r}' # 4 mm
    rmin = 0
    nr = '${n_elem}'   # number of radial elements
    nt = '${n_elem}'   # number of tangential elements
  []

[]

[Variables]
  # We solve for the temperature and the displacements
  [./T]
    family = LAGRANGE
    order = FIRST
  [../]
[]

[Functions]
  [./analytic_solution]
    type =  ParsedFunction
    # Expected parabolic profile for temperature in UO2 pellet
   expression = '3.98e8/(4*${k})*${r}^2*(1-(x^2+y^2)/${r}^2)+700'
  [../]
[]

[Kernels]

  [./symbolic_diffusion_kernel]
    type = MatDiffusion   # evaluate the divergence of a flux
    variable = T
    diffusivity = k
    # the thermal_conductivity/ diffusion_coefficient and their derivatives
    # can be symbolically evaluated form a DerivativeParsedMaterial
    # to be defined under the Materials block if temperature-dependent
  [../]
  [./heat_source]
    type = HeatSource
    variable = T
    value = 3.98e8  #W/m3
  [../]

[]
[BCs]

[./Outer_T] #Temperature on outer edge
  type = DirichletBC
  variable = T
  value = ${T_edge}
  boundary = rmax
[../]

[]

[Materials]
  [./thermal_conductivity]
    type = DerivativeParsedMaterial
    property_name = k
    expression = ${k} #W/mK
    derivative_order = 0
    #expression = 'a0:=0.1148;a1:=0.0035;b0:=0.0002474;b1:=-8e-7;c:=0.0132;d:=0.00188; ((1/((a0+a1*75)+(b0+b1*75)*(T-273.15))+c*exp(d*(T-273.15))))'
    #coupled_variables = 'T'
  [../]
[]

[Preconditioning]
  [./smp]
    type = SMP
    full = true
  [../]
[]

[Postprocessors]
  [./Average_temperature]
    type = ElementAverageValue
    variable = T
  [../]
  [./Average_error] # difference between numerical and analtical solutions averaged over the entire pellet(L2 norm)
    type = ElementL2Error
    variable = T
    function = analytic_solution
  [../]
  [./Center_temperature]
    type = PointValue
     point = '0 0 0'
    variable = T
  [../]
[]


[Executioner]
  type = Steady
  solve_type = PJFNK
  petsc_options_iname = '-pc_type -pc_factor_mat_solving_package'
  petsc_options_value = 'lu superlu_dist'
  nl_rel_tol = 1e-8
  nl_abs_tol = 1e-11
  l_tol = 1e-3
  l_max_its = 30
  nl_max_its = 10
[]

[Outputs]
  file_base = uo2_linear_thermal_steady/uo2_linear_thermal_steady_k=${k}
  exodus = true
  csv = true

[]
